### ISSUE TITLE
Listing your package on Pulsar

### ISSUE THREAD

**Issue by confused-Techie** [bacadra/atom-bib-finder#2]
Hello, this is confused-Techie from the Pulsar Team!

I was originally going to reach out to you about the license in your package, not being clear if it was available for redistribution. Seems the version we got from the Atom Archive was outdated, as I see now you have a license available.

In which case I saw your readme about not being able to list your package. And wanted to bring to your attention [Pulsar](https://github.com/pulsar-edit/pulsar).

We are the actively developed fork of Atom, and have a functional Package Registry, allowing users to install packages that were previously available on Atom, and for users to publish new ones. If you'd like feel free to upload your package there, or if you'd like we can remove it from our registry, as the license we have from you does not make it clear if we can redistribute.

Either way thanks for your time, and would be happy to hear from you!

---

Edit my above comment applies additionally to:
* image-paste
* word-map
* sofistik-tools
* hydrogen-run
* autocomplete-sofistik

**Comment by asiloisad** [comment]
Hi, I'm already aware of the Pulsar project and I follow your progress. I'm waiting for the moment when it be possible to run the Hydrogen package without any problems & Pulsar come out of beta, then I will want to port all my packages to Pulsar. However, if want to redistribute to Pulsar Package REgistry now - do not hesitate. Best regards, SB

**Comment by confused-Techie** [comment]
@asiloisad Thanks a ton!

Just to let you know, seems Hydrogens major issue is the way they [parse the Pulsar version](https://github.com/nteract/hydrogen/pull/2162), which while resolved on their main branch, hasn't been updated to Pulsar, so you could potentially install their package via git, which has seen improvements on Pulsar, or we are soon going to release our next beta version, whose tag will let them parse it properly.

Otherwise I understand wanting to wait till things are more stable.

Appreciate your time and response, have a nice day!
